// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJwd3QtWIa1pUcIXVA-YBS5sAmtiZ-tgA',
    appId: '1:633725393991:web:7ace5e49feca4fd37aa562',
    messagingSenderId: '633725393991',
    projectId: 'mytodotasks-f7029',
    authDomain: 'mytodotasks-f7029.firebaseapp.com',
    storageBucket: 'mytodotasks-f7029.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4GyLOFkZ3qeNy2sob8jHwYKdGhf4g3wE',
    appId: '1:633725393991:android:fa7933611e7163ed7aa562',
    messagingSenderId: '633725393991',
    projectId: 'mytodotasks-f7029',
    storageBucket: 'mytodotasks-f7029.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC06rAvqbW_RqDio50Qpqrcx6dt2mvYIY4',
    appId: '1:633725393991:ios:4c1d1d5f4f6c5bf77aa562',
    messagingSenderId: '633725393991',
    projectId: 'mytodotasks-f7029',
    storageBucket: 'mytodotasks-f7029.firebasestorage.app',
    iosBundleId: 'com.example.todoTaskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC06rAvqbW_RqDio50Qpqrcx6dt2mvYIY4',
    appId: '1:633725393991:ios:4c1d1d5f4f6c5bf77aa562',
    messagingSenderId: '633725393991',
    projectId: 'mytodotasks-f7029',
    storageBucket: 'mytodotasks-f7029.firebasestorage.app',
    iosBundleId: 'com.example.todoTaskApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJwd3QtWIa1pUcIXVA-YBS5sAmtiZ-tgA',
    appId: '1:633725393991:web:99582b4d15ec61df7aa562',
    messagingSenderId: '633725393991',
    projectId: 'mytodotasks-f7029',
    authDomain: 'mytodotasks-f7029.firebaseapp.com',
    storageBucket: 'mytodotasks-f7029.firebasestorage.app',
  );
}
